"""add is_read to messages

Revision ID: 6311029c6f5e
Revises: 20a2f6d86399
Create Date: 2026-04-28 21:06:50.893162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6311029c6f5e'
down_revision: Union[str, Sequence[str], None] = '20a2f6d86399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages',
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
