"""added education

Revision ID: de1a0991da47
Revises: 5f752900b247
Create Date: 2026-04-18 12:35:45.936642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1a0991da47'
down_revision: Union[str, Sequence[str], None] = '5f752900b247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tutors', sa.Column('education_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'tutors', ['education_id'])
    op.create_foreign_key(None, 'tutors', 'educations', ['education_id'], ['id'])
    op.drop_column('tutors', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tutors', type_='foreignkey')
    op.drop_constraint(None, 'tutors', type_='unique')
    op.drop_column('tutors', 'education_id')
    op.drop_table('educations')
    # ### end Alembic commands ###
